<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/30 08:50:02
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
