<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/08/29 17:55:13
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 5,
));
