<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/30 12:00:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeetTest',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
