<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/29 10:59:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeetTest',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
