<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/31 11:04:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
