<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/31 10:46:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
