# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# proyect rules

job:
  class:              sfDoctrineRouteCollection
  options:
    model:            JobeetJob
    column:           token
    object_actions:
      publish:        put
  requeriments:
      token:          \w+

job_show_user:
  url:                /job/:company_slug/:location_slug/:id/:position_slug
  class:              sfDoctrineRoute
  options:
    model:            JobeetJob
    type:             object
    method_for_query: retrieveActiveJob
  param:
    module:           job
    action:           show
  requeriments:
    id:               \d+
    sf_method:        [get]

category:
  url:                /category/:slug
  class:              sfDoctrineRoute
  options:
    model:            JobeetCategory
    type:             object
  param:
    module:           category
    action:           show

# default rules
homepage:
  url:   /
  param:
    module:           job
    action:           index