<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }

    //	Retorna todos los Jobs activos
    public function getActivesJobs(Doctrine_Query $query = null){
        /*$query = is_null($query) ? Doctrine_Query::create()->from('JobeetJob j') : $query;

        return $query->andWhere('j.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->addOrderBy('j.expires_at DESC')
            ->execute();*/

        return $this->addActiveJobsQuery($query)->execute();
    }

    //  Retorna un Job en caso de no haber expirado
    public function retrieveActiveJob(Doctrine_Query $query = null){
        /*$query = is_null($query) ? Doctrine_Query::create()->from('JobeetJob j') : $query;

        return $query->andWhere('a.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->fetchOne();*/
        return $this->addActiveJobsQuery($query)->fetchOne();
    }

    //  Retorna la cantidad de Jobs
    public function countActiveJobs(Doctrine_Query $query = null){
        return $this->addActiveJobsQuery($query)->count();
    }

    public function addActiveJobsQuery(Doctrine_Query $query = null){
        $query = is_null($query) ? Doctrine_Query::create()->from('JobbetJob j') : $query;
        $alias = $query->getRootAlias();

        return $query->andWhere($alias . '.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->addOrderBy($alias . '.expires_at DESC');
    }
}