<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
	//	Retorna una lista de Jobs pertenecientes a una dicha (this) categoria
    public function getActiveJobs($max = 10){
  		/*$query = Doctrine_Query::create()
    	->from('JobeetJob j')
    	->where('j.category_id = ?', $this->getId())
    	->limit($max);
 
  		return Doctrine_Core::getTable('JobeetJob')->getActivesJobs($query);*/
  		return $this->getActiveJobsQuery()
  			->limit($max)
  			->execute();
	}

	//	Retorna el nombre para mostrar en URL (no se utiliza xq se modifico el schema para slug)
	/*public function getSlug(){
		return Jobeet::slugify($this->getName());
	}*/

	//	Retorna la cantidad de Jobs actives de la categoria
	public function countActiveJobs(){
		/*$query = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId());

		return Doctrine_Core::getTable('JobeetJob')->countActiveJobs($query);*/
		return $this->getActiveJobsQuery()->count();
	}

	public function getActiveJobsQuery(){
		$query = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId());

		return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($query);
	}
}
