<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
	//	Retorna una lista de Jobs pertenecientes a una dicha (this) categoria
    public function getActiveJobs($max = 10){
  		return $this->getActiveJobsQuery()
  			->limit($max)
  			->execute();
	}

	//	Retorna la cantidad de Jobs actives de la categoria
	public function countActiveJobs(){
		return $this->getActiveJobsQuery()->count();
	}

	//	Retorna la consulta con la que trabajan los demas metodos
	public function getActiveJobsQuery(){
		$query = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId());

		return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($query);
	}
}
