<?php

/**
 * JobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetCategory');
    }

    //	Retorna una lista de categorias con al menos un Job
    public function getWithJobs(){
    	return $this->createQuery('c')
    		->leftJoin('c.JobeetJobs j')
    		->where('j.expires_at > ?', Jobeet::getTime())
    		->execute();
    }
}