generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, slug]
        title:  Category Manegement
        # configurando que columnas muestro
        batch_actions: {}
        object_actions: {}
      filter:
        display: [=name, slug]
      form:
        display: [=name]
      edit:
        title:  Editing Category "%%name%%"
      new:
        title:  New category
