<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/08/31 15:52:00
$this->security = array (
  'category' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
