<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/08/31 15:53:38
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
