generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Jobeetjob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeetjob
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
      #    nivel general
      fields:
        is_activated:
          label:  Activated?
          help:   Whether the user has activated the job, or not
        is_public:
          label:  Public?
          help:   Whether the job can also be published on affiliate websites, or not
      list:
        title:    Job Management
        layout:   stacked
        display:  [company, position, location, url, is_activated, email]
        params:   |
                  %%is_activated%% <small>%%jobeet_category%%</small> - %%company%%
                  (<em>%%email%%</em>) is looking for a %%=position%% (%%location%%))
        sort:     [expires_at, desc]
        max_per_page: 10
        batch_actions:
          _delete: ~
          extend: ~
        object_actions:
          extend:  ~
          _edit:    ~
          _delete:  ~
        actions:
          deleteNeverActivated:
            label: Delete never activated jobs
        table_method: retrieveBackendJobList
      filter:
        # indico los filros que quiero mostrar
        display: [category_id, company, position, description, is_activated, is_public, email]
      form:
        class:  BackendJobeetJobForm
        display:
          Content:  [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
          Admin:    [_generated_token, is_activated, expires_at]
      
      # hereda de from, que hereda de fields, pero puede modificarlos
      edit:
        title:  Editing Job "%%company%%" is looking for a %%position%%
      
      # hereda de from, que hereda de fields, pero puede modificarlos
      new:
        title:  Job Creation
        display: [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
